services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: bianca23
      POSTGRES_USER: cinesystem
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"
